modLoader="javafml"
loaderVersion="[51,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Backpacks/issues"
license="Apache-2.0 License"

[[mods]]
	modId="usefulbackpacks"
	version="${file.jarVersion}"
	displayName="Useful Backpacks"
	displayURL="https://u-team.info/mods/usefulbackpacks"
	updateJSONURL="https://api.u-team.info/update/usefulbackpacks.json"
	logoFile="logo.png"
	credits="Team U-Team"
	authors="HyCraftHD"
	description="Join our discord server here: https://discord.hycrafthd.net\n\nThis mod adds cool new backpacks to your game."
	
	[[dependencies.usefulbackpacks]]
	    modId="forge"
	    mandatory=true
	    versionRange="[51.0.26,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulbackpacks]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.21]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulbackpacks]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[5.6.0.317,)"
	    ordering="NONE"
	    side="BOTH"