modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Backpacks/issues"
license="Apache-2.0 License"

[[mods]]
	modId="usefulbackpacks"
	version="${file.jarVersion}"
	displayName="Useful Backpacks"
	displayURL="https://u-team.info/mods/usefulbackpacks"
	updateJSONURL="https://api.u-team.info/update/usefulbackpacks_neoforge.json"
	logoFile="logo.png"
	credits="Team U-Team"
	authors="HyCraftHD"
	description="Join our discord server here: https://discord.hycrafthd.net\n\nThis mod adds cool new backpacks to your game."
	
	[[dependencies.usefulbackpacks]]
		modId="neoforge"
		type="required"
		versionRange="[21.0.113-beta,)"
		ordering="NONE"
		side="BOTH"
	
	[[dependencies.usefulbackpacks]]
		modId="minecraft"
		type="required"
		versionRange="[1.21]"
		ordering="NONE"
		side="BOTH"
	    
	[[dependencies.usefulbackpacks]]
		modId="uteamcore"
		type="required"
		versionRange="[5.6.0.317,)"
		ordering="NONE"
		side="BOTH"
		
[[mixins]]
	config = "usefulbackpacks.mixins.json"